application:
  port: 8000
  # Must set `APP_APPLICATION__HMAC_SECRET` env variable on Digial Ocean for production
hmac_secret: "long-and-secret-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@example.com"
  authorization_token: "123-45-6789"
  timeout_milliseconds: 10000
